server:
  port: 8773
spring:
  profiles:
    active: dev
  application:
    name: service-task
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
#redis-cache 相关
redis:
  pool:
    maxActive: 300
    maxIdle: 100
    maxWait: 10000
    #需要修改地址
#  host: ${REDIS_HOST:127.0.0.1}
  host: ${REDIS_HOST:192.168.1.4}
  port:  ${REDIS_PORT:6379}
  password: 123456
  timeout: 20000
  # 服务或应用名
  sysName: service_task
  enable: true
  database: 6

mybatis:
  mapper-locations: classpath:mapper/*.xml
logging:
  level:
    com.github.hollykunge.security.data.mapper: debug
    tk.mybatis: debug
